include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
  errors:
    unused_import: ignore # Đặt mức độ thành warning, không phải error
    unnecessary_import: ignore
    deprecated_member_use: ignore
    avoid_print: ignore # Bỏ qua cảnh báo về print
    use_build_context_synchronously: ignore

linter:
  rules:
    # Tắt một số rule nếu cần
    avoid_print: false
    use_build_context_synchronously: false
