// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRvBsDzuulAbijvjHA3ywS9jK9RjLngKY',
    appId: '1:331500783813:web:a60d2f778194824dca48ac',
    messagingSenderId: '331500783813',
    projectId: 'expense-tracker-f255c',
    authDomain: 'expense-tracker-f255c.firebaseapp.com',
    storageBucket: 'expense-tracker-f255c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ex_jap6cRKdK3MPoeziDKWk655kjHR4',
    appId: '1:331500783813:android:56a32b0e9a9bc0c6ca48ac',
    messagingSenderId: '331500783813',
    projectId: 'expense-tracker-f255c',
    storageBucket: 'expense-tracker-f255c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIoet65I2M8pXtqFm9AXR8eWI569k6fcs',
    appId: '1:331500783813:ios:ecc1b06cbd06bf3bca48ac',
    messagingSenderId: '331500783813',
    projectId: 'expense-tracker-f255c',
    storageBucket: 'expense-tracker-f255c.firebasestorage.app',
    iosBundleId: 'com.example.blocExpensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIoet65I2M8pXtqFm9AXR8eWI569k6fcs',
    appId: '1:331500783813:ios:ecc1b06cbd06bf3bca48ac',
    messagingSenderId: '331500783813',
    projectId: 'expense-tracker-f255c',
    storageBucket: 'expense-tracker-f255c.firebasestorage.app',
    iosBundleId: 'com.example.blocExpensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRvBsDzuulAbijvjHA3ywS9jK9RjLngKY',
    appId: '1:331500783813:web:55e009d31cb964f8ca48ac',
    messagingSenderId: '331500783813',
    projectId: 'expense-tracker-f255c',
    authDomain: 'expense-tracker-f255c.firebaseapp.com',
    storageBucket: 'expense-tracker-f255c.firebasestorage.app',
  );
}
