name: Flutter CI/CD # Tên workflow

on: # Sự kiện kích hoạt workflow
  push:
    branches: [ "main" ] # Chạy khi đẩy mã lên nhánh main
  pull_request:
    branches: [ "main" ] # Chạy khi tạo pull request vào main
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest # Máy ảo Linux

    steps:
      # Bước 1: Clone mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Java (cần cho Android build)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Bước 3: Cài đặt Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Phiên bản Flutter cụ thể
          channel: 'stable'

      # Bước 4: Lấy các thư viện
      - name: Get dependencies
        run: flutter pub get

      # Bước 5: Kiểm tra định dạng mã
      # - name: Check formatting
      #   run: dart format --set-exit-if-changed .

      # Bước 6: Phân tích mã (linter)
      - name: Analyze code
        run: flutter analyze

      # Bước 7: Chạy unit tests
      - name: Run tests
        run: flutter test

      # Bước 8: Xây dựng AppBundle cho Android
      - name: Build AppBundle
        run: flutter build appbundle --release

      # Bước 9: Lưu AppBundle làm artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab